/* Wanderly Camera Studio — on-device filters, no third-party account required. */
const wc={stream:null,facing:'user',filter:'natural',photo:null,busy:false};
const WC_FILTERS={natural:['Natural','none'],glow:['Soft glow','brightness(1.09) contrast(.95) saturate(1.16)'],golden:['Golden hour','sepia(.23) saturate(1.32) brightness(1.07)'],vintage:['Vintage','sepia(.48) contrast(.92) saturate(.84)'],mono:['Black & white','grayscale(1) contrast(1.13)'],cool:['Cool blue','saturate(1.1) hue-rotate(15deg) contrast(1.06)'],dream:['Dreamy','brightness(1.12) saturate(.82) contrast(.89)'],vivid:['Vivid','saturate(1.65) contrast(1.13)']};
function camera(){return `<section class="section"><span class="tag">WANDERLY CAMERA STUDIO</span><h1>Capture the beautiful moments 📷</h1><p>Take photos with live color filters, save them to your memory book or share them using your phone's share sheet.</p><div class="wc-stage"><video id="wcVideo" autoplay playsinline muted aria-label="Camera preview"></video><img id="wcShot" alt="Your captured photograph" hidden><div id="wcEmpty">Tap “Start camera” to begin. Allow camera access when asked.</div></div><p id="wcStatus" class="small" role="status">Camera is off.</p><div class="wc-controls"><button class="primary" onclick="wcStart()">📷 Start camera</button><button class="ghost" onclick="wcFlip()">↻ Flip</button><button class="ghost" onclick="wcStop()">■ Stop</button></div><h2>Choose your look ✨</h2><div class="wc-filters">${Object.entries(WC_FILTERS).map(([id,a])=>`<button class="${wc.filter===id?'wc-active':''}" onclick="wcChoose('${id}')" type="button">${a[0]}</button>`).join('')}</div><div class="wc-controls"><button class="primary" onclick="wcCapture()">◉ Capture photo</button><button class="ghost" onclick="wcSave()">↓ Save photo</button><button class="ghost" onclick="wcMemory()">♡ Add to collage</button><button class="ghost" onclick="wcShare()">↗ Share / Snapchat</button></div><p class="note">Snapchat sharing uses your device's share sheet when supported. Snapchat's official AR Lenses require a separate Snap Camera Kit integration and approved credentials; these are Wanderly's own color filters, not Snapchat Lenses.</p></section>`}
function wcStatus(s){let e=document.getElementById('wcStatus');if(e)e.textContent=s}
async function wcStart(){if(!navigator.mediaDevices?.getUserMedia){wcStatus('Camera requires HTTPS or localhost and a supported browser.');return}wcStop(false);try{let stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:wc.facing},width:{ideal:1920},height:{ideal:1080}}});wc.stream=stream;let v=document.getElementById('wcVideo');if(!v){stream.getTracks().forEach(t=>t.stop());return}v.srcObject=stream;v.hidden=false;document.getElementById('wcShot').hidden=true;document.getElementById('wcEmpty').hidden=true;v.style.filter=WC_FILTERS[wc.filter][1];await v.play();wcStatus('Camera ready. Choose a filter and capture.')}catch(e){wcStatus(e.name==='NotAllowedError'?'Camera permission denied. Enable it in your browser settings.':'Camera unavailable: '+e.message)}}
function wcStop(message=true){if(wc.stream){wc.stream.getTracks().forEach(t=>t.stop());wc.stream=null}let v=document.getElementById('wcVideo');if(v){v.srcObject=null;v.hidden=true}if(message)wcStatus('Camera stopped.')}
async function wcFlip(){wc.facing=wc.facing==='user'?'environment':'user';await wcStart()}
function wcChoose(id){if(!WC_FILTERS[id])return;wc.filter=id;let v=document.getElementById('wcVideo');if(v)v.style.filter=WC_FILTERS[id][1];document.querySelectorAll('.wc-filters button').forEach(b=>b.classList.toggle('wc-active',b.textContent===WC_FILTERS[id][0]));wcStatus(WC_FILTERS[id][0]+' filter selected.');}
function wcCapture(){let v=document.getElementById('wcVideo');if(!v||!wc.stream||!v.videoWidth){wcStatus('Start the camera before capturing.');return}let c=document.createElement('canvas');let scale=Math.min(1,2000/Math.max(v.videoWidth,v.videoHeight));c.width=Math.max(1,Math.round(v.videoWidth*scale));c.height=Math.max(1,Math.round(v.videoHeight*scale));let x=c.getContext('2d');x.filter=WC_FILTERS[wc.filter][1];if(wc.facing==='user'){x.translate(c.width,0);x.scale(-1,1)}x.drawImage(v,0,0,c.width,c.height);wc.photo=c.toDataURL('image/jpeg',.91);let shot=document.getElementById('wcShot');shot.src=wc.photo;shot.hidden=false;v.hidden=true;wcStatus('Photo captured! Save, add to collage or share.');}
function wcBlob(){if(!wc.photo){wcStatus('Capture a photo first.');return null}let [head,b64]=wc.photo.split(',');let raw=atob(b64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type:'image/jpeg'})}
function wcSave(){let blob=wcBlob();if(blob)download(blob,'wanderly-camera-'+Date.now()+'.jpg')}
function wcMemory(){if(!wc.photo){wcStatus('Capture a photo first.');return}try{data.photos.push({src:wc.photo,place:'Camera memory'});save();wcStatus('Added to your memory book. Open Gallery to create a collage.')}catch(e){wcStatus('Could not save photo. Free up browser storage or download it instead.')}}
async function wcShare(){let blob=wcBlob();if(!blob)return;let file=new File([blob],'wanderly-memory.jpg',{type:'image/jpeg'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Wanderly memory'});wcStatus('Shared using your device. Choose Snapchat if it appears in the share sheet.')}else{wcSave();wcStatus('Photo downloaded. Open Snapchat and upload it from your gallery.')}}catch(e){if(e.name!=='AbortError')wcStatus('Sharing unavailable. Save the photo and upload it in Snapchat.')}}
